# most of the setting copied from https://github.com/weiaicunzai/pytorch-cifar100
# training settings
seed: 6660857
dataset: cifar100
strategy: baseline
update-cycle: 25
batch_size: 128
epochs: 200
save-freq: 10

# model settings
arch: resnet18
lr_scheduler:
  type: multistep #multistep #cosine
  lr: 0.1
  milestones: [60, 120, 160]
  gamma: 0.2
  T_0: 1
  T_mult: 1
  eta_min: 0.01
momentum: 0.9
weight_decay: 0.0005
